### ISSUE TITLE
Missing domain

### ISSUE THREAD

**Issue by ellwoods** [Jumoo/Jumoo.PageSpeedyPlus#3]
Hi, I'm not sure this is the correct place to let you know however  you seem to have totally overlooked North East Lincs - https://www.nelincs.gov.uk/ 

If you have any specific questions regarding this or North lincs I may be able to help

regards

**Comment by KevinJump** [comment]
Hi, thanks getting an accurate list of councils and websites is surprisingly hard. 

but North East Lincs is there http://jumoo.uk/speedy/speedy.php?id=265

**Comment by ellwoods** [comment]
My apologies for the oversight. Council lists are available though I’m not sure the same for websites is.
